apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapi-deployment
  labels:
    app: goapi
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: goapi
  template:
    metadata:
      labels:
        app: goapi
    spec:
      containers:
      - name: goapi
        imagePullPolicy: Never
        image: docker.io/vaugenwake/goapi:latest
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: goapi-service
spec:
  type: NodePort
  selector:
    app: goapi
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 3000