apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel
data:
  APP_NAME: laravel
  APP_ENV: production
  APP_DEBUG: "false"
  APP_URL: http://localhost
  LOG_CHANNEL: stderr
  LOG_LEVEL: debug
  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  QUEUE_CONNECTION: sync
  SESSION_DRIVER: file
  SESSION_LIFETIME: "120"
  MAIL_MAILER: smtp
  MAIL_HOST: smtp.mailtrap.io
  MAIL_PORT: "2525"
  MAIL_USERNAME: 'null'
  MAIL_PASSWORD: 'null'
  MAIL_ENCRYPTION: tls