# This will create a single Pod running a 
# single Nginx container on port 80
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:stable-alpine
    resources:
      limits:
        memory: "50Mi"
        cpu: "250m" # 1 core/vCPU = 1000 millicpu units
    ports:
      - containerPort: 80
